### ISSUE TITLE
Clear cache when toggling device emulation mode

### ISSUE THREAD

**Issue by nhardy** [xobotyi/scrollbar-width#2]
**Is your feature request related to a problem? Please describe.**

Scroll bar width can change when toggling device emulation mode. (e.g. 17px to 0px, vice-versa)

**Describe the solution you'd like**

Listen to window resize events and automatically clear the cache, or provide a more clear interface to clear the cache (`__cache` feels too much like an internal that consumers shouldn't touch). 

**Describe alternatives you've considered**

Consumers of the package requiring this functionality can listen to window resize events and manually `delete scrollbarWidth.__cache;`

**Comment by xobotyi** [comment]
Actually it is intended to be set to `undefined`/deleted by consumers when the need package to recalc sbw.

I'll clarify it in readme later.

**Comment by xobotyi** [comment]
Btw, you can get recalculated and recached value if call function with `true` parameter.
